/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 port.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/port.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[1249.743, -294.534, 1358.154]}>
          <mesh geometry={nodes.Cube_61.geometry} material={nodes.Cube_61.material} position={[-236.325, 29.785, 92.692]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cube_62.geometry} material={nodes.Cube_62.material} position={[116.987, 0.788, -1.372]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cube_60.geometry} material={nodes.Cube_60.material} position={[-589.637, 0.788, -1.372]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cube_62_1.geometry} material={nodes.Cube_62_1.material} position={[116.987, 0.788, 186.757]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cube_59.geometry} material={nodes.Cube_59.material} position={[-589.637, 0.788, 186.757]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cylinder_29.geometry} material={nodes.Cylinder_29.material} position={[180.417, -24.378, -154.825]} scale={1.559} />
        </group>
        <group position={[-1456.151, -316.858, -608.771]}>
          <group position={[121.13, 0.217, 10.403]} rotation={[0, -1.363, Math.PI / 2]} scale={0.342}>
            <mesh geometry={nodes.Sphere_17.geometry} material={nodes.Sphere_17.material} position={[8.889, 21.116, -92.57]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Sphere_16.geometry} material={nodes.Sphere_16.material} position={[58.807, 21.116, -92.57]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Cube_13_2.geometry} material={nodes.Cube_13_2.material} position={[-21.202, -3.808, 45.527]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
          </group>
          <group position={[106.539, 6.319, 40.923]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.342}>
            <mesh geometry={nodes.Sphere_13.geometry} material={nodes.Sphere_13.material} position={[3.074, 21.116, -9.903]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Sphere_12.geometry} material={nodes.Sphere_12.material} position={[3.074, 21.116, -57.961]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Cube_11_2.geometry} material={nodes.Cube_11_2.material} position={[34.611, -3.808, 20.043]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <group position={[-27.631, -31.981, 189.691]} scale={0.342}>
            <mesh geometry={nodes.Sphere_8.geometry} material={nodes.Sphere_8.material} position={[18.545, 21.116, -17.158]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Sphere_9.geometry} material={nodes.Sphere_9.material} position={[-28.101, 21.116, 3.605]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Cube_18_1.geometry} material={nodes.Cube_18_1.material} position={[11.818, -3.808, 6.723]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <group position={[-112.433, -4.798, 1.853]} rotation={[Math.PI / 2, 0, 0]} scale={0.342}>
            <mesh geometry={nodes.Cube_20_1.geometry} material={nodes.Cube_20_1.material} position={[0.419, -3.808, -27.002]} rotation={[-Math.PI / 2, 0, 0]} />
            <mesh geometry={nodes.Sphere_14.geometry} material={nodes.Sphere_14.material} position={[-39.195, 21.116, -43.323]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Sphere_13_1.geometry} material={nodes.Sphere_13_1.material} position={[4.896, 21.116, -43.323]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
          </group>
          <mesh geometry={nodes.X.geometry} material={nodes.X.material} position={[-124.986, -27.609, -92.781]} rotation={[-Math.PI / 2, 0, 3.026]} scale={2.637} />
          <mesh geometry={nodes.B.geometry} material={nodes.B.material} position={[-33.148, -27.609, -132.346]} rotation={[-Math.PI / 2, 0, 0.83]} scale={2.637} />
          <mesh geometry={nodes['7'].geometry} material={nodes['7'].material} position={[53.55, -27.556, -73.382]} rotation={[-Math.PI / 2, 0, 0.31]} scale={2.64} />
          <mesh geometry={nodes.Star_2.geometry} material={nodes.Star_2.material} position={[40.166, -34.945, -173.271]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Boolean_16.geometry} material={nodes.Boolean_16.material} position={[4.011, -22.913, -51.075]} rotation={[0, 1.457, 0]} />
        </group>
        <group position={[718.746, -313.864, 385.705]}>
          <group position={[-264.502, -23.705, -127.289]} rotation={[0, 0.436, -Math.PI / 2]}>
            <mesh geometry={nodes.Sphere_3.geometry} material={nodes.Sphere_3.material} position={[0, 25.364, 0]} rotation={[-Math.PI / 2, 0, 0]} />
            <mesh geometry={nodes.Cube_3_2.geometry} material={nodes.Cube_3_2.material} position={[0, -25.364, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <group position={[9.009, -6.967, 170.768]} rotation={[Math.PI / 2, 0, 0]} scale={0.342}>
            <mesh geometry={nodes.Sphere_3_1.geometry} material={nodes.Sphere_3_1.material} position={[31.815, 21.116, -9.87]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Sphere_3_2.geometry} material={nodes.Sphere_3_2.material} position={[-26.102, 21.116, -9.87]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Cube_3_3.geometry} material={nodes.Cube_3_3.material} position={[-1.129, -3.808, 7.567]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <group position={[266.37, -28.7, -88.219]} rotation={[0, 0.587, 0]} scale={0.342}>
            <mesh geometry={nodes.Sphere_8_1.geometry} material={nodes.Sphere_8_1.material} position={[-34.733, 21.116, -33.926]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Cube_8_3.geometry} material={nodes.Cube_8_3.material} position={[18.41, -3.808, 10.933]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <group position={[-181.046, 1.292, -139.171]} rotation={[Math.PI / 2, 0, Math.PI / 4]} scale={0.448}>
            <mesh geometry={nodes.Sphere_5.geometry} material={nodes.Sphere_5.material} position={[-31.938, 21.116, -38.681]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Cube_5_4.geometry} material={nodes.Cube_5_4.material} position={[13.234, -3.808, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <group position={[55.876, 0.24, 169.664]} rotation={[Math.PI, 0, -Math.PI / 2]} scale={0.342}>
            <mesh geometry={nodes.Sphere_4.geometry} material={nodes.Sphere_4.material} position={[21.893, 21.116, -31.113]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Sphere_4_1.geometry} material={nodes.Sphere_4_1.material} position={[22.584, 21.116, 38.595]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Cube_4_3.geometry} material={nodes.Cube_4_3.material} position={[-1.129, -3.808, 7.567]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <group position={[29.397, -3.479, 54.025]} rotation={[Math.PI / 2, 0, 0]} scale={0.342}>
            <mesh geometry={nodes.Sphere_13_2.geometry} material={nodes.Sphere_13_2.material} position={[3.243, 21.116, -51.338]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Cube_24_1.geometry} material={nodes.Cube_24_1.material} position={[0, -3.808, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <mesh geometry={nodes.Z.geometry} material={nodes.Z.material} position={[-91.592, -30.603, -234.612]} rotation={[-Math.PI / 2, 0, 0.72]} scale={2.637} />
          <mesh geometry={nodes.C.geometry} material={nodes.C.material} position={[2.118, -30.603, -194.041]} rotation={[-Math.PI / 2, 0, 0]} scale={2.637} />
          <mesh geometry={nodes.V.geometry} material={nodes.V.material} position={[9.071, -30.603, 124.467]} rotation={[-Math.PI / 2, 0, 0]} scale={2.637} />
          <mesh geometry={nodes.N.geometry} material={nodes.N.material} position={[114.467, -30.603, 426.091]} rotation={[-Math.PI / 2, 0, 0.489]} scale={2.637} />
          <mesh geometry={nodes['4'].geometry} material={nodes['4'].material} position={[160.407, -30.55, -127.242]} rotation={[-Math.PI / 2, 0, 0]} scale={2.64} />
          <mesh geometry={nodes['5'].geometry} material={nodes['5'].material} position={[-128.014, -30.55, -162.042]} rotation={[-Math.PI / 2, 0, 0]} scale={2.64} />
          <mesh geometry={nodes.Cube_55.geometry} material={nodes.Cube_55.material} position={[38.525, -22.175, -407.551]} rotation={[-Math.PI / 2, 0, -0.162]} />
          <mesh geometry={nodes.Triangle_7.geometry} material={nodes.Triangle_7.material} position={[-169.608, -30.666, -254.32]} rotation={[-Math.PI / 2, 0, 1.262]} />
          <mesh geometry={nodes.Boolean_3.geometry} material={nodes.Boolean_3.material} position={[55.708, -25.907, -22.026]} />
          <mesh geometry={nodes.Boolean_5.geometry} material={nodes.Boolean_5.material} position={[207.049, -25.907, 29.248]} rotation={[0, 0.996, 0]} />
          <mesh geometry={nodes.Boolean_2.geometry} material={nodes.Boolean_2.material} position={[-60.354, -25.907, 26.007]} rotation={[0, 0.996, 0]} />
          <mesh geometry={nodes.Boolean_4.geometry} material={nodes.Boolean_4.material} position={[138.503, -25.907, 89.168]} />
          <mesh geometry={nodes.Boolean.geometry} material={nodes.Boolean.material} position={[108.778, -14.6, -12.354]} rotation={[0, 0, -0.392]} />
        </group>
        <group position={[728.581, -104.461, 917.76]} scale={1.996}>
          <mesh geometry={nodes.Cube_53.geometry} material={nodes.Cube_53.material} position={[-2.828, 98, 1.243]} rotation={[-Math.PI / 2, 0, -0.766]} />
          <mesh geometry={nodes.Cube_53_1.geometry} material={nodes.Cube_53_1.material} position={[2.922, 49, -1.825]} rotation={[-Math.PI / 2, 0, -0.862]} />
          <mesh geometry={nodes.Cube_53_2.geometry} material={nodes.Cube_53_2.material} position={[1.221, 0, 0.828]} rotation={[-Math.PI / 2, 0, -0.572]} />
          <mesh geometry={nodes.Cube_53_3.geometry} material={nodes.Cube_53_3.material} position={[-1.509, -49, -0.923]} rotation={[-Math.PI / 2, 0, -0.425]} />
          <mesh geometry={nodes.Cube_53_4.geometry} material={nodes.Cube_53_4.material} position={[-1.439, -98, 2.329]} rotation={[-Math.PI / 2, 0, -0.598]} />
        </group>
        <group position={[1184.928, -249.246, 400.098]}>
          <group position={[211.276, -55.246, -348.777]} rotation={[0, 0.168, 0]}>
            <mesh geometry={nodes.Cylinder_10_3.geometry} material={nodes.Cylinder_10_3.material} position={[0, -45, 0]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1, 1.815, 1]} />
            <mesh geometry={nodes.Cylinder_8_3.geometry} material={nodes.Cylinder_8_3.material} position={[0, -45, 0.03]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1, 1.812, 1]} />
            <mesh geometry={nodes.Cylinder_6_4.geometry} material={nodes.Cylinder_6_4.material} position={[0, -45, 0.03]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1, 1.812, 1]} />
            <mesh geometry={nodes.Cylinder_4_3.geometry} material={nodes.Cylinder_4_3.material} position={[0, -45, 0.03]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1, 1.812, 1]} />
          </group>
          <group position={[252.075, -55.246, -138.77]}>
            <mesh geometry={nodes.Cylinder_10_4.geometry} material={nodes.Cylinder_10_4.material} position={[0, -45, 66.809]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1, 1.677, 1.127]} />
            <mesh geometry={nodes.Cylinder_8_4.geometry} material={nodes.Cylinder_8_4.material} position={[0, -45, 21.367]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1, 1.675, 1.127]} />
            <mesh geometry={nodes.Cylinder_6_5.geometry} material={nodes.Cylinder_6_5.material} position={[0, -45, -21.64]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1, 1.675, 1.127]} />
            <mesh geometry={nodes.Cylinder_4_4.geometry} material={nodes.Cylinder_4_4.material} position={[0, -45, -66.837]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1, 1.675, 1.127]} />
          </group>
          <group position={[-1.157, -55.246, -370.976]} rotation={[0, -1.122, 0]}>
            <mesh geometry={nodes.Cylinder_10_5.geometry} material={nodes.Cylinder_10_5.material} position={[0, -45, 0]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1, 2.464, 1]} />
            <mesh geometry={nodes.Cylinder_9_1.geometry} material={nodes.Cylinder_9_1.material} position={[0, -45, 0]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1, 2.464, 1]} />
            <mesh geometry={nodes.Cylinder_8_5.geometry} material={nodes.Cylinder_8_5.material} position={[0, -45, 0]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1, 2.464, 1]} />
            <mesh geometry={nodes.Cylinder_7_2.geometry} material={nodes.Cylinder_7_2.material} position={[0, -45, 0]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1, 2.464, 1]} />
            <mesh geometry={nodes.Cylinder_6_6.geometry} material={nodes.Cylinder_6_6.material} position={[0, -45, 0]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1, 2.464, 1]} />
            <mesh geometry={nodes.Cylinder_5_1.geometry} material={nodes.Cylinder_5_1.material} position={[0, -45, 0]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1, 2.464, 1]} />
            <mesh geometry={nodes.Cylinder_4_5.geometry} material={nodes.Cylinder_4_5.material} position={[0, -45, 0]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1, 2.464, 1]} />
          </group>
          <group position={[28.474, -71.562, -218.005]} rotation={[-Math.PI / 2, 0, 2.543]} scale={0.342}>
            <mesh geometry={nodes.Sphere_15.geometry} material={nodes.Sphere_15.material} position={[74.33, 21.103, -48.965]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Sphere_14_1.geometry} material={nodes.Sphere_14_1.material} position={[-75.635, 21.103, -48.965]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Cube_12_3.geometry} material={nodes.Cube_12_3.material} position={[-13.574, -3.794, 9.899]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
          </group>
          <group position={[-12.897, -99.602, 56.15]} rotation={[0, -0.598, 0]} scale={0.342}>
            <mesh geometry={nodes.Sphere_13_3.geometry} material={nodes.Sphere_13_3.material} position={[1.611, 21.142, -48.168]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Cube_22_2.geometry} material={nodes.Cube_22_2.material} position={[12.668, -4.08, -13.128]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <group position={[-131.706, -99.602, 408.033]} rotation={[0, -1.227, 0]} scale={0.342}>
            <mesh geometry={nodes.Sphere_3_3.geometry} material={nodes.Sphere_3_3.material} position={[27.73, 21.116, -34.394]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Sphere_3_4.geometry} material={nodes.Sphere_3_4.material} position={[-30.187, 21.116, -34.394]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Cube_1.geometry} material={nodes.Cube_1.material} position={[0, -3.808, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <mesh geometry={nodes.M.geometry} material={nodes.M.material} position={[103.264, -95.221, -250.413]} rotation={[-Math.PI / 2, 0, -1.054]} scale={2.637} />
          <mesh geometry={nodes.J.geometry} material={nodes.J.material} position={[82.868, -95.221, 9.351]} rotation={[-Math.PI / 2, 0, 0.621]} scale={2.637} />
          <mesh geometry={nodes['2'].geometry} material={nodes['2'].material} position={[-229.167, -95.168, -180.819]} rotation={[-Math.PI / 2, 0, 0.92]} scale={2.64} />
          <mesh geometry={nodes['8'].geometry} material={nodes['8'].material} position={[-50.342, -95.168, -79.476]} rotation={[-Math.PI / 2, 0, -0.286]} scale={2.64} />
          <mesh geometry={nodes.Cube_52.geometry} material={nodes.Cube_52.material} position={[-30.578, -88.067, -166.04]} rotation={[-Math.PI / 2, 0, 0.326]} />
          <mesh geometry={nodes.Cone_12.geometry} material={nodes.Cone_12.material} position={[-316.063, -90.775, 394.277]} rotation={[-Math.PI, -1.207, 1.294]} />
          <mesh geometry={nodes.Cube_16.geometry} material={nodes.Cube_16.material} position={[33.74, -75.254, -73.649]} rotation={[-Math.PI / 2, 0, -0.478]} />
          <mesh geometry={nodes.Cube_15.geometry} material={nodes.Cube_15.material} position={[142.63, -75.254, 34.059]} rotation={[-Math.PI / 2, 0, -0.478]} />
          <mesh geometry={nodes.Cube_14.geometry} material={nodes.Cube_14.material} position={[174.139, -75.254, 103.536]} rotation={[-Math.PI / 2, 0, -0.738]} />
          <mesh geometry={nodes.Cube_13.geometry} material={nodes.Cube_13.material} position={[-19.595, -75.254, 438.017]} rotation={[-Math.PI / 2, 0, -0.01]} />
          <mesh geometry={nodes.Cube_12.geometry} material={nodes.Cube_12.material} position={[-228.746, -75.254, 210.971]} rotation={[-Math.PI / 2, 0, -0.01]} />
          <mesh geometry={nodes.Cube_11.geometry} material={nodes.Cube_11.material} position={[-283.845, -75.254, 185.346]} rotation={[-Math.PI / 2, 0, -0.661]} />
          <mesh geometry={nodes.Cube_9.geometry} material={nodes.Cube_9.material} position={[-219.02, -26.254, 343.214]} rotation={[-Math.PI / 2, 0, -0.539]} />
          <mesh geometry={nodes.Cube_8.geometry} material={nodes.Cube_8.material} position={[-219.02, -75.254, 343.214]} rotation={[-Math.PI / 2, 0, -0.766]} />
          <mesh geometry={nodes.Cube_7.geometry} material={nodes.Cube_7.material} position={[40.523, 120.746, 99.489]} rotation={[-Math.PI / 2, 0, -0.766]} />
          <mesh geometry={nodes.Cube_6.geometry} material={nodes.Cube_6.material} position={[46.273, 71.746, 96.421]} rotation={[-Math.PI / 2, 0, -0.862]} />
          <mesh geometry={nodes.Cube_5.geometry} material={nodes.Cube_5.material} position={[44.572, 22.746, 99.074]} rotation={[-Math.PI / 2, 0, -0.572]} />
          <mesh geometry={nodes.Cube_4.geometry} material={nodes.Cube_4.material} position={[41.842, -26.254, 97.324]} rotation={[-Math.PI / 2, 0, -0.425]} />
          <mesh geometry={nodes.Cube_3.geometry} material={nodes.Cube_3.material} position={[41.912, -75.254, 100.575]} rotation={[-Math.PI / 2, 0, -0.598]} />
        </group>
        <group position={[832.897, -212.616, -530.931]}>
          <group position={[55.561, -102.104, 17.839]} rotation={[0, -0.015, 0]}>
            <mesh geometry={nodes.Sphere_6.geometry} material={nodes.Sphere_6.material} position={[0, 25.364, 0]} rotation={[-Math.PI / 2, 0, 0]} />
            <mesh geometry={nodes.Cube_3_4.geometry} material={nodes.Cube_3_4.material} position={[0, -25.364, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <group position={[-280.519, -97.331, -50.245]}>
            <mesh geometry={nodes.Sphere_7.geometry} material={nodes.Sphere_7.material} position={[0, 25.364, 0]} rotation={[-Math.PI / 2, 0, 0]} />
            <mesh geometry={nodes.Cube_3_5.geometry} material={nodes.Cube_3_5.material} position={[0, -25.364, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <group position={[-6.911, -136.019, 19.446]} scale={0.342}>
            <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[0.101, -3.827, -1.594]} />
            <mesh geometry={nodes.Sphere_14_2.geometry} material={nodes.Sphere_14_2.material} position={[-21.909, 20.519, -14.789]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Sphere_13_4.geometry} material={nodes.Sphere_13_4.material} position={[20.972, 20.519, -14.789]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
          </group>
          <mesh geometry={nodes.A.geometry} material={nodes.A.material} position={[-371.017, -131.851, -15.873]} rotation={[-Math.PI / 2, 0, 0]} scale={2.637} />
          <mesh geometry={nodes['9'].geometry} material={nodes['9'].material} position={[87.847, -131.798, 340.355]} rotation={[-Math.PI / 2, 0, 0.769]} scale={2.64} />
          <mesh geometry={nodes.Triangle_3.geometry} material={nodes.Triangle_3.material} position={[-271.678, 76.194, -142.577]} rotation={[0, -Math.PI / 9, 0]} scale={0.78} />
          <mesh geometry={nodes.Triangle_2.geometry} material={nodes.Triangle_2.material} position={[114.621, -137.485, 26.773]} rotation={[-Math.PI / 2, 0, -1.339]} />
          <mesh geometry={nodes.Triangle_4.geometry} material={nodes.Triangle_4.material} position={[180.878, -137.609, -118.011]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} scale={[1.414, 1.414, 1]} />
          <mesh geometry={nodes.Triangle.geometry} material={nodes.Triangle.material} position={[-148.067, 134.516, -97.586]} rotation={[0, -Math.PI / 9, 0]} scale={[1.414, 1.414, 1]} />
          <mesh geometry={nodes.Boolean_9.geometry} material={nodes.Boolean_9.material} position={[-432.054, -123.423, -97.288]} rotation={[-Math.PI / 2, 0, 0.172]} />
          <mesh geometry={nodes.Boolean_12.geometry} material={nodes.Boolean_12.material} position={[-355.003, -131.398, -201.325]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} />
          <mesh geometry={nodes.Boolean_8.geometry} material={nodes.Boolean_8.material} position={[-369.118, -5.562, -162.546]} rotation={[0, -Math.PI / 9, 0]} />
          <mesh geometry={nodes.Cone_6.geometry} material={nodes.Cone_6.material} position={[443.439, -103.773, -245.65]} rotation={[0, -Math.PI / 9, 0]} />
          <mesh geometry={nodes.Cone_8.geometry} material={nodes.Cone_8.material} position={[-359.096, -125.751, -92.717]} rotation={[0, -Math.PI / 9, 0]} />
          <mesh geometry={nodes.Cone_10.geometry} material={nodes.Cone_10.material} position={[158.25, -124.937, -400.381]} rotation={[0, -Math.PI / 9, 0]} />
          <mesh geometry={nodes.Cone_9.geometry} material={nodes.Cone_9.material} position={[188.321, 38.813, -232.038]} rotation={[0, -Math.PI / 9, 0]} />
          <mesh geometry={nodes.Cylinder_7.geometry} material={nodes.Cylinder_7.material} position={[190.888, 10.579, -230.879]} rotation={[0, -0.816, 0]} />
          <mesh geometry={nodes.Cylinder_5.geometry} material={nodes.Cylinder_5.material} position={[90.556, -48.105, -353.494]} rotation={[0, -0.816, 0]} />
          <mesh geometry={nodes.Cylinder_9.geometry} material={nodes.Cylinder_9.material} position={[160.158, -123.336, 65.134]} rotation={[0, 0.436, -Math.PI / 2]} />
          <mesh geometry={nodes.Cylinder_28.geometry} material={nodes.Cylinder_28.material} position={[72.227, -120.027, 210.311]} rotation={[0, 0.471, -Math.PI / 2]} />
          <mesh geometry={nodes.Cylinder_8.geometry} material={nodes.Cylinder_8.material} position={[-329.663, -129.457, 28.523]} rotation={[0, 0.011, -Math.PI / 2]} />
          <mesh geometry={nodes.Cylinder_4.geometry} material={nodes.Cylinder_4.material} position={[-409.78, -112.17, -177.346]} rotation={[0, -Math.PI / 9, 0]} />
          <mesh geometry={nodes.Pyramid_3.geometry} material={nodes.Pyramid_3.material} position={[108.641, -56.202, -229.073]} rotation={[0, -0.816, 0]} />
          <mesh geometry={nodes.Pyramid_2.geometry} material={nodes.Pyramid_2.material} position={[64.181, -116.661, -382.111]} rotation={[0, -0.816, 0]} />
          <mesh geometry={nodes.Cube_14_1.geometry} material={nodes.Cube_14_1.material} position={[21.84, -99.273, -20.249]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} />
          <mesh geometry={nodes.Cube_14_2.geometry} material={nodes.Cube_14_2.material} position={[-76.507, -99.273, -56.044]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} />
          <mesh geometry={nodes.Cube_8_1.geometry} material={nodes.Cube_8_1.material} position={[-229.588, -99.273, -108.505]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} />
          <mesh geometry={nodes.Cube_8_2.geometry} material={nodes.Cube_8_2.material} position={[-327.935, -99.273, -147.557]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} />
          <mesh geometry={nodes.Cube_5_1.geometry} material={nodes.Cube_5_1.material} position={[-103.874, -26.179, -66.005]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} />
          <mesh geometry={nodes.Cube_5_2.geometry} material={nodes.Cube_5_2.material} position={[-103.874, -100.179, -66.005]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} />
          <mesh geometry={nodes.Boolean_10.geometry} material={nodes.Boolean_10.material} position={[-27.3, -62.104, -38.238]} rotation={[0, -Math.PI / 9, 0]} />
          <mesh geometry={nodes.Boolean_7.geometry} material={nodes.Boolean_7.material} position={[-278.728, -62.104, -129.751]} rotation={[0, -Math.PI / 9, 0]} />
          <mesh geometry={nodes.Boolean_11.geometry} material={nodes.Boolean_11.material} position={[108.511, -123.144, 193.19]} rotation={[-Math.PI / 2, 0, -1.077]} />
          <mesh geometry={nodes.Boolean_6.geometry} material={nodes.Boolean_6.material} position={[-153.014, 10.99, -83.994]} rotation={[0, -Math.PI / 9, 0]} />
          <mesh geometry={nodes.Cube_13_1.geometry} material={nodes.Cube_13_1.material} position={[-275.562, 49.766, -131.905]} rotation={[0, 1.222, -Math.PI / 2]} scale={0.78} />
          <mesh geometry={nodes.Cube_54.geometry} material={nodes.Cube_54.material} position={[39.458, -126.252, 164.394]} rotation={[0, 0.811, -Math.PI / 2]} />
          <mesh geometry={nodes.Cube_53_5.geometry} material={nodes.Cube_53_5.material} position={[-23.146, -126.252, 258.415]} rotation={[0, 0.204, -Math.PI / 2]} />
          <mesh geometry={nodes.Cube_58.geometry} material={nodes.Cube_58.material} position={[11.337, -97.129, 179.171]} rotation={[-Math.PI, 0.758, Math.PI / 2]} />
          <mesh geometry={nodes.Cube_7_1.geometry} material={nodes.Cube_7_1.material} position={[-20.164, -126.252, 190.733]} rotation={[0, 1.222, -Math.PI / 2]} />
          <mesh geometry={nodes.Cube_27.geometry} material={nodes.Cube_27.material} position={[185.439, -123.047, -13.08]} rotation={[0, 1.222, -Math.PI]} scale={[1.414, 1, 1.414]} />
          <mesh geometry={nodes.Cube_6_1.geometry} material={nodes.Cube_6_1.material} position={[-153.047, 86.593, -83.903]} rotation={[0, 1.222, -Math.PI / 2]} scale={[1.414, 1, 1.414]} />
          <mesh geometry={nodes.Cube_29.geometry} material={nodes.Cube_29.material} position={[85.863, -123.047, -92.717]} rotation={[0, 0.447, -Math.PI / 2]} />
          <mesh geometry={nodes.Cube_18.geometry} material={nodes.Cube_18.material} position={[136.931, -123.047, -226.006]} rotation={[0, 0.929, -Math.PI / 2]} />
          <mesh geometry={nodes.Cube_20.geometry} material={nodes.Cube_20.material} position={[180.108, -93.924, -225.248]} rotation={[-Math.PI, 0.903, Math.PI / 2]} />
          <mesh geometry={nodes.Cube_19.geometry} material={nodes.Cube_19.material} position={[133.344, -93.924, -252.299]} rotation={[Math.PI, 0.729, Math.PI / 2]} />
          <mesh geometry={nodes.Cube_17.geometry} material={nodes.Cube_17.material} position={[175.613, -123.047, -263.025]} rotation={[0, 0.755, -Math.PI / 2]} />
          <mesh geometry={nodes.Cube_21.geometry} material={nodes.Cube_21.material} position={[190.888, -40.59, -230.879]} rotation={[-Math.PI / 2, 0, -0.816]} />
          <mesh geometry={nodes.Cube_15_1.geometry} material={nodes.Cube_15_1.material} position={[90.556, -99.273, -353.494]} rotation={[-Math.PI / 2, 0, -0.816]} />
          <mesh geometry={nodes.Cube_10.geometry} material={nodes.Cube_10.material} position={[-382.669, -99.273, -167.478]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} />
          <mesh geometry={nodes.Cube_12_1.geometry} material={nodes.Cube_12_1.material} position={[-290.092, 15.7, -133.783]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} scale={[1, 1, 0.614]} />
          <mesh geometry={nodes.Cube_12_2.geometry} material={nodes.Cube_12_2.material} position={[-262.725, 15.7, -123.822]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} scale={[1, 1, 0.614]} />
          <mesh geometry={nodes.Cube_9_1.geometry} material={nodes.Cube_9_1.material} position={[-355.302, -99.273, -154.261]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} />
          <mesh geometry={nodes.Cube_4_1.geometry} material={nodes.Cube_4_1.material} position={[-202.221, -26.179, -98.544]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} />
          <mesh geometry={nodes.Cube_3_1.geometry} material={nodes.Cube_3_1.material} position={[-202.221, -100.179, -101.801]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} />
          <mesh geometry={nodes.Cube_56.geometry} material={nodes.Cube_56.material} position={[-392.629, -123.423, -49.279]} rotation={[-Math.PI / 2, 0, 0.289]} />
          <mesh geometry={nodes.Cube_32.geometry} material={nodes.Cube_32.material} position={[-15.487, -29.876, 126.363]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} />
          <mesh geometry={nodes.Cube_31.geometry} material={nodes.Cube_31.material} position={[-15.487, -58.999, 126.363]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} />
          <mesh geometry={nodes.Cube_30.geometry} material={nodes.Cube_30.material} position={[-15.487, -88.122, 126.363]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} />
          <mesh geometry={nodes.Cube_30_1.geometry} material={nodes.Cube_30_1.material} position={[-15.487, -116.012, 123.107]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} />
          <mesh geometry={nodes.Cube_11_1.geometry} material={nodes.Cube_11_1.material} position={[-368.985, -20.123, -159.242]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} />
          <mesh geometry={nodes.Cube_2.geometry} material={nodes.Cube_2.material} position={[-368.985, -48.013, -162.498]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} />
          <mesh geometry={nodes.Star_3.geometry} material={nodes.Star_3.material} position={[-21.06, -139.187, -119.294]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cone_3.geometry} material={nodes.Cone_3.material} position={[127.199, -101.376, 395.737]} />
          <mesh geometry={nodes.Cone_11.geometry} material={nodes.Cone_11.material} position={[28.607, -127.405, 340.178]} rotation={[0, 0.674, -1.848]} />
          <mesh geometry={nodes.Cone_2.geometry} material={nodes.Cone_2.material} position={[36.556, -101.376, 258.415]} />
        </group>
        <group position={[416.12, -364.395, -72.043]} scale={[1.229, 1.551, 1.229]}>
          <group position={[-12.718, -19.192, 0.332]} rotation={[0, 0.334, 0]}>
            <mesh geometry={nodes.Sphere_10.geometry} material={nodes.Sphere_10.material} position={[0, 25.364, 0]} rotation={[-Math.PI / 2, 0, 0]} />
            <mesh geometry={nodes.Cube_3_6.geometry} material={nodes.Cube_3_6.material} position={[0, -25.364, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <group position={[-56.89, 8.434, -140.839]} rotation={[0, 0.334, 0]} scale={0.703}>
            <mesh geometry={nodes.Cone_3_1.geometry} material={nodes.Cone_3_1.material} position={[0, 54.674, 0]} />
            <mesh geometry={nodes.Cone_2_1.geometry} material={nodes.Cone_2_1.material} position={[0, 24.584, 0]} />
            <mesh geometry={nodes.Cone_1.geometry} material={nodes.Cone_1.material} position={[0, -6.58, 0]} />
            <mesh geometry={nodes.Cylinder_3.geometry} material={nodes.Cylinder_3.material} position={[0.624, -72.792, -0.984]} />
          </group>
          <group position={[57.649, 8.434, 33.821]} rotation={[0, 0.334, 0]} scale={0.703}>
            <mesh geometry={nodes.Cone_3_2.geometry} material={nodes.Cone_3_2.material} position={[0, 54.674, 0]} />
            <mesh geometry={nodes.Cone_2_2.geometry} material={nodes.Cone_2_2.material} position={[0, 24.584, 0]} />
            <mesh geometry={nodes.Cone_4.geometry} material={nodes.Cone_4.material} position={[0, -6.58, 0]} />
            <mesh geometry={nodes.Cylinder_3_1.geometry} material={nodes.Cylinder_3_1.material} position={[0.624, -72.792, -0.984]} />
          </group>
          <group position={[21.182, -34.42, 120.94]} rotation={[0, 1.189, 0]}>
            <group position={[-0.52, -14.659, 0]}>
              <mesh geometry={nodes.Cylinder_5_2.geometry} material={nodes.Cylinder_5_2.material} position={[11.666, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.Cylinder_4_6.geometry} material={nodes.Cylinder_4_6.material} position={[-11.666, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.Cylinder_5_3.geometry} material={nodes.Cylinder_5_3.material} position={[11.666, 0, -14.052]} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.Cylinder_3_4.geometry} material={nodes.Cylinder_3_4.material} position={[-11.666, 0, -14.052]} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.Cylinder_5_4.geometry} material={nodes.Cylinder_5_4.material} position={[11.666, 0, 13.939]} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.Cylinder_2_1.geometry} material={nodes.Cylinder_2_1.material} position={[-11.666, 0, 13.939]} rotation={[Math.PI / 2, 0, 0]} />
            </group>
            <mesh geometry={nodes.Cylinder_2.geometry} material={nodes.Cylinder_2.material} position={[-0.345, -6.148, -0.089]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
            <mesh geometry={nodes.Cube_3_7.geometry} material={nodes.Cube_3_7.material} position={[0.174, -10.585, -0.135]} />
          </group>
          <group position={[-65.481, -58.137, 144.212]} rotation={[0, -0.321, 0]} scale={0.342}>
            <mesh geometry={nodes.Sphere_11.geometry} material={nodes.Sphere_11.material} position={[-1.363, 19.761, -41.512]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Cube_25_1.geometry} material={nodes.Cube_25_1.material} position={[0, -5.163, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <mesh geometry={nodes.L.geometry} material={nodes.L.material} position={[24.341, -54.219, -46.121]} rotation={[-Math.PI / 2, 0, -0.525]} scale={2.637} />
        </group>
        <group position={[-33.551, -340.296, 835.833]}>
          <mesh geometry={nodes.R.geometry} material={nodes.R.material} position={[108.266, -4.171, -18.768]} rotation={[-Math.PI / 2, 0, 0]} scale={2.637} />
          <mesh geometry={nodes.E.geometry} material={nodes.E.material} position={[-10.556, -4.171, -123.894]} rotation={[-Math.PI / 2, 0, 0.489]} scale={2.637} />
          <mesh geometry={nodes.S.geometry} material={nodes.S.material} position={[223.189, -4.171, -99.955]} rotation={[-Math.PI / 2, 0, 1.488]} scale={2.637} />
          <mesh geometry={nodes.A_1.geometry} material={nodes.A_1.material} position={[176.669, -4.171, -81.255]} rotation={[-1.262, 0.046, 0.143]} scale={2.637} />
          <mesh geometry={nodes.Star.geometry} material={nodes.Star.material} position={[108.094, -6.486, -168.935]} rotation={[-Math.PI / 2, 0, 0.978]} />
          <mesh geometry={nodes.Boolean_6_1.geometry} material={nodes.Boolean_6_1.material} position={[47.095, 14.089, 56.193]} rotation={[0, 0.326, 0]} />
          <mesh geometry={nodes.Cube_4_2.geometry} material={nodes.Cube_4_2.material} position={[9.193, 49.183, -45.959]} rotation={[-Math.PI / 2, 0, 0.326]} />
          <mesh geometry={nodes.Triangle_2_1.geometry} material={nodes.Triangle_2_1.material} position={[129.292, -4.234, 108.526]} rotation={[-Math.PI / 2, 0, 1.262]} />
          <mesh geometry={nodes.Cylinder_7_1.geometry} material={nodes.Cylinder_7_1.material} position={[-164.694, 2.748, 192.64]} rotation={[0, 0.326, 0]} />
          <mesh geometry={nodes.Cylinder_6.geometry} material={nodes.Cylinder_6.material} position={[-180.895, 3.748, 78.702]} rotation={[0, 0.326, 0]} />
          <mesh geometry={nodes.Cube_5_3.geometry} material={nodes.Cube_5_3.material} position={[-64.682, 39.16, 19.014]} rotation={[-Math.PI / 2, 0, 0.853]} />
        </group>
        <group position={[-22.96, -271.756, -566.99]}>
          <group position={[-182.67, -54.314, 161.209]} rotation={[0, 0.334, -1.762]} scale={0.703}>
            <mesh geometry={nodes.Cone_3_3.geometry} material={nodes.Cone_3_3.material} position={[0, 54.674, 0]} />
            <mesh geometry={nodes.Cone_2_3.geometry} material={nodes.Cone_2_3.material} position={[0, 24.584, 0]} />
            <mesh geometry={nodes.Cone_13.geometry} material={nodes.Cone_13.material} position={[0, -6.58, 0]} />
            <mesh geometry={nodes.Cylinder_3_2.geometry} material={nodes.Cylinder_3_2.material} position={[0.624, -72.792, -0.984]} />
          </group>
          <group position={[-26.837, -0.274, -158.539]} rotation={[Math.PI / 2, 0, 0]} scale={0.342}>
            <mesh geometry={nodes.Sphere_11_1.geometry} material={nodes.Sphere_11_1.material} position={[-39.726, 21.116, -67.057]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Sphere_10_1.geometry} material={nodes.Sphere_10_1.material} position={[1.192, 21.116, -67.057]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Cube_10_1.geometry} material={nodes.Cube_10_1.material} position={[7.983, -3.808, 10.947]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <group position={[-31.026, -53.927, -155.937]} rotation={[0, -Math.PI / 4, -Math.PI / 2]} scale={0.342}>
            <mesh geometry={nodes.Sphere_7_1.geometry} material={nodes.Sphere_7_1.material} position={[-29.857, 21.116, 50.83]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Sphere_6_1.geometry} material={nodes.Sphere_6_1.material} position={[-29.857, 21.116, -55.442]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Cube_7_2.geometry} material={nodes.Cube_7_2.material} position={[7.983, -3.808, 10.947]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <group position={[-49.042, -69.659, 116.435]} rotation={[Math.PI, 0.846, Math.PI]} scale={0.342}>
            <mesh geometry={nodes.Sphere_4_2.geometry} material={nodes.Sphere_4_2.material} position={[21.893, 21.116, -31.113]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Sphere_4_3.geometry} material={nodes.Sphere_4_3.material} position={[22.584, 21.116, 38.595]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Cube_4_4.geometry} material={nodes.Cube_4_4.material} position={[-1.129, -3.808, 7.567]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <mesh geometry={nodes['1'].geometry} material={nodes['1'].material} position={[171.489, -72.658, -97.352]} rotation={[-Math.PI / 2, 0, -0.511]} scale={2.64} />
          <mesh geometry={nodes['6'].geometry} material={nodes['6'].material} position={[30.393, -72.658, -165.55]} rotation={[-Math.PI / 2, 0, 0.709]} scale={2.64} />
          <mesh geometry={nodes.Triangle_6.geometry} material={nodes.Triangle_6.material} position={[15.253, -78.468, 169.725]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} scale={[1.414, 1.414, 1]} />
          <mesh geometry={nodes.Boolean_14.geometry} material={nodes.Boolean_14.material} position={[-2.776, -64.283, 50.802]} rotation={[-Math.PI / 2, 0, 1.27]} />
          <mesh geometry={nodes.Cone_7.geometry} material={nodes.Cone_7.material} position={[93.622, 39.27, 7.52]} rotation={[0, -Math.PI / 9, 0]} />
          <mesh geometry={nodes.Cone_5.geometry} material={nodes.Cone_5.material} position={[182.049, -44.633, 118.004]} rotation={[0, -Math.PI / 9, 0]} />
          <mesh geometry={nodes.Cylinder_6_1.geometry} material={nodes.Cylinder_6_1.material} position={[93.615, 11.035, 7.506]} rotation={[0, -Math.PI / 9, 0]} />
          <mesh geometry={nodes.Cube_26.geometry} material={nodes.Cube_26.material} position={[84.345, 92.53, 109.664]} rotation={[0, 1.222, -Math.PI / 2]} />
          <mesh geometry={nodes.Cube_25.geometry} material={nodes.Cube_25.material} position={[69.449, 48.03, 104.242]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} />
          <mesh geometry={nodes.Cube_24.geometry} material={nodes.Cube_24.material} position={[96.425, 48.03, 112.846]} rotation={[-Math.PI / 2, 0, 0.175]} />
          <mesh geometry={nodes.Cube_22.geometry} material={nodes.Cube_22.material} position={[108.296, -40.133, 116.88]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} />
          <mesh geometry={nodes.Cube_22_1.geometry} material={nodes.Cube_22_1.material} position={[31.347, -40.133, 88.873]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} />
          <mesh geometry={nodes.Boolean_13.geometry} material={nodes.Boolean_13.material} position={[25.746, -64.004, -58.352]} rotation={[-Math.PI / 2, 0, 0.562]} />
          <mesh geometry={nodes.Cube_16_1.geometry} material={nodes.Cube_16_1.material} position={[93.615, -40.133, 7.506]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} />
          <mesh geometry={nodes.Cube_28.geometry} material={nodes.Cube_28.material} position={[23.21, -63.907, -33.56]} rotation={[-Math.PI, Math.PI / 9, 0]} scale={[1, 1, 0.614]} />
          <mesh geometry={nodes.Cube_23.geometry} material={nodes.Cube_23.material} position={[69.931, 3.097, 102.917]} rotation={[0, 1.222, -Math.PI / 2]} />
          <mesh geometry={nodes.Cube_57.geometry} material={nodes.Cube_57.material} position={[160.391, -64.283, -78.45]} rotation={[-Math.PI / 2, 0, 0.013]} />
          <mesh geometry={nodes.Boolean_16_1.geometry} material={nodes.Boolean_16_1.material} position={[213.695, -68.015, -1.477]} rotation={[0, 0.461, 0]} />
        </group>
        <group position={[-744.973, -196.389, 1439.96]}>
          <mesh geometry={nodes.Cylinder_31.geometry} material={nodes.Cylinder_31.material} position={[-332.027, -36.251, 320.108]} scale={[1, 0.703, 1]} />
          <mesh geometry={nodes.Cylinder_21.geometry} material={nodes.Cylinder_21.material} position={[332.027, -41.982, 276.116]} scale={[1, 0.703, 1]} />
          <mesh geometry={nodes.Cylinder_20.geometry} material={nodes.Cylinder_20.material} position={[320.009, -44.197, -320.108]} scale={[1, 0.703, 1]} />
          <mesh geometry={nodes.Cylinder_19.geometry} material={nodes.Cylinder_19.material} position={[8.831, 8.136, 179.521]} />
          <mesh geometry={nodes.Cylinder_18.geometry} material={nodes.Cylinder_18.material} position={[-185.027, -42.595, -243.225]} scale={[1, 0.703, 1]} />
        </group>
        <group position={[-79.323, -285.036, 1424.139]}>
          <mesh geometry={nodes.Shape_2.geometry} material={nodes.Shape_2.material} position={[172.342, -65.791, 160.215]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.Shape.geometry} material={nodes.Shape.material} position={[-172.342, -65.791, -158.747]} />
          <mesh geometry={nodes.Cylinder_22.geometry} material={nodes.Cylinder_22.material} position={[-326.408, 47.407, 0]} scale={[1, 0.5, 1]} />
          <mesh geometry={nodes.Cube_49.geometry} material={nodes.Cube_49.material} position={[0, -18.208, 0]} />
          <mesh geometry={nodes.Cube_50.geometry} material={nodes.Cube_50.material} position={[326.408, -18.208, 0]} />
          <mesh geometry={nodes.Cube_48.geometry} material={nodes.Cube_48.material} position={[-326.408, -18.208, 0]} />
        </group>
        <group position={[-1048.468, -312.959, -537.798]}>
          <mesh geometry={nodes.Cylinder_27.geometry} material={nodes.Cylinder_27.material} position={[69.749, 52.287, -154.082]} rotation={[-1.506, -0.14, 1.823]} scale={[0.656, 0.328, 0.656]} />
          <mesh geometry={nodes.Cylinder_26.geometry} material={nodes.Cylinder_26.material} position={[-56.738, 45.721, -36.484]} rotation={[-1.544, 0, 0.27]} scale={[0.656, 0.225, 0.656]} />
          <mesh geometry={nodes.Cylinder_25.geometry} material={nodes.Cylinder_25.material} position={[55.176, -11.003, -45.234]} scale={[0.656, 0.225, 0.656]} />
          <mesh geometry={nodes.Cylinder_24.geometry} material={nodes.Cylinder_24.material} position={[-85.501, 0.5, 81.133]} scale={[0.656, 0.328, 0.656]} />
        </group>
        <group position={[2048.351, -302.846, 72.32]}>
          <mesh geometry={nodes.Cube_49_1.geometry} material={nodes.Cube_49_1.material} position={[83.5, -23.944, 0.17]} rotation={[0, -Math.PI / 2, 0]} scale={[1, 0.412, 1]} />
          <mesh geometry={nodes.Cube_50_1.geometry} material={nodes.Cube_50_1.material} position={[-83.5, 0, -327.285]} rotation={[0, -Math.PI / 2, 0]} scale={[1, 0.417, 1]} />
          <mesh geometry={nodes.Cube_48_1.geometry} material={nodes.Cube_48_1.material} position={[-83.5, 0, 327.285]} rotation={[0, -Math.PI / 2, 0]} scale={[1, 0.417, 1]} />
        </group>
        <group position={[498.01, -182, -1399.529]}>
          <mesh geometry={nodes.Cube_46.geometry} material={nodes.Cube_46.material} position={[146.707, 83.5, 47.999]} rotation={[-Math.PI / 2, 0, 1.267]} />
          <mesh geometry={nodes.Cube_45.geometry} material={nodes.Cube_45.material} position={[91.895, -83.5, 30.789]} rotation={[-Math.PI / 2, 0, 1.267]} />
          <mesh geometry={nodes.Cube_47.geometry} material={nodes.Cube_47.material} position={[-232.489, -83.5, -87.755]} rotation={[-Math.PI / 2, 0, 0.675]} />
          <mesh geometry={nodes.Cube_44.geometry} material={nodes.Cube_44.material} position={[245.176, -83.5, 100.442]} rotation={[-Math.PI / 2, 0, 1.267]} />
        </group>
        <group position={[1687.562, -205.06, 790.935]} rotation={[0, Math.PI / 2, 0]}>
          <mesh geometry={nodes.Cylinder_31_1.geometry} material={nodes.Cylinder_31_1.material} position={[220.38, -102.8, 3.05]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1.155, 2.556, 1.155]} />
          <mesh geometry={nodes.Cylinder_30.geometry} material={nodes.Cylinder_30.material} position={[176.268, -11.555, 3.05]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1.155, 2.556, 1.155]} />
          <mesh geometry={nodes.Cylinder_29_1.geometry} material={nodes.Cylinder_29_1.material} position={[97.661, 51.201, 3.05]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1.155, 2.556, 1.155]} />
          <mesh geometry={nodes.Cylinder_28_1.geometry} material={nodes.Cylinder_28_1.material} position={[-1.314, 74.025, 3.05]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1.155, 2.556, 1.155]} />
          <mesh geometry={nodes.Cylinder_27_1.geometry} material={nodes.Cylinder_27_1.material} position={[-99.777, 51.549, 3.05]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1.155, 2.556, 1.155]} />
          <mesh geometry={nodes.Cylinder_26_1.geometry} material={nodes.Cylinder_26_1.material} position={[-178.915, -11.235, 3.05]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1.155, 2.556, 1.155]} />
          <mesh geometry={nodes.Cylinder_25_1.geometry} material={nodes.Cylinder_25_1.material} position={[-221.711, -101.614, 3.05]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1.155, 2.556, 1.155]} />
          <mesh geometry={nodes.Cylinder_10.geometry} material={nodes.Cylinder_10.material} position={[0, -142.686, -132.406]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[3.171, 2.93, 3.171]} />
          <mesh geometry={nodes.Cylinder_8_1.geometry} material={nodes.Cylinder_8_1.material} position={[0, -142.686, -132.357]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[3.171, 2.925, 3.171]} />
          <mesh geometry={nodes.Cylinder_6_2.geometry} material={nodes.Cylinder_6_2.material} position={[0, -142.686, -132.357]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[3.171, 2.925, 3.171]} />
          <mesh geometry={nodes.Cylinder_4_1.geometry} material={nodes.Cylinder_4_1.material} position={[0, -142.686, -132.357]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[3.171, 2.925, 3.171]} />
          <mesh geometry={nodes.Cylinder_10_1.geometry} material={nodes.Cylinder_10_1.material} position={[0, -142.686, 132.406]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[3.171, 2.93, 3.171]} />
          <mesh geometry={nodes.Cylinder_8_2.geometry} material={nodes.Cylinder_8_2.material} position={[0, -142.686, 132.454]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[3.171, 2.925, 3.171]} />
          <mesh geometry={nodes.Cylinder_6_3.geometry} material={nodes.Cylinder_6_3.material} position={[0, -142.686, 132.454]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[3.171, 2.925, 3.171]} />
          <mesh geometry={nodes.Cylinder_4_2.geometry} material={nodes.Cylinder_4_2.material} position={[0, -142.686, 132.454]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[3.171, 2.925, 3.171]} />
        </group>
        <group position={[-1431.765, -224.979, 837.872]} scale={1.158}>
          <mesh geometry={nodes.Cube_48_2.geometry} material={nodes.Cube_48_2.material} position={[-219.723, -82.09, -166.846]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cube_47_1.geometry} material={nodes.Cube_47_1.material} position={[219.649, -82.09, -166.846]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cube_48_3.geometry} material={nodes.Cube_48_3.material} position={[-219.723, -82.09, 166.773]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cube_46_1.geometry} material={nodes.Cube_46_1.material} position={[219.649, -82.09, 166.773]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Shape_1.geometry} material={nodes.Shape_1.material} position={[-302.706, -108.912, -116.371]} />
          <mesh geometry={nodes.Cube_44_1.geometry} material={nodes.Cube_44_1.material} position={[-2.287, -103.648, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cube_45_1.geometry} material={nodes.Cube_45_1.material} position={[155.074, -67.217, 0.208]} rotation={[0, 0, -Math.PI / 2]} scale={[0.611, 0.611, 1]} />
          <mesh geometry={nodes.Cylinder_19_1.geometry} material={nodes.Cylinder_19_1.material} position={[0.029, -27.659, -166.988]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={1.124} />
          <mesh geometry={nodes.Cylinder_18_1.geometry} material={nodes.Cylinder_18_1.material} position={[0.029, -27.659, 166.282]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={1.124} />
        </group>
        <group position={[-1431.438, -181.717, 69.805]} scale={1.158}>
          <mesh geometry={nodes.Cube_43.geometry} material={nodes.Cube_43.material} position={[0.363, -103.31, -146.746]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cube_42.geometry} material={nodes.Cube_42.material} position={[-0.282, -104.564, 136.168]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.611, 0.611, 1]} />
          <mesh geometry={nodes.Boolean_15.geometry} material={nodes.Boolean_15.material} position={[-0.282, 45.085, -0.011]} />
          <mesh geometry={nodes.Cube_40.geometry} material={nodes.Cube_40.material} position={[-0.282, -118.036, -0.924]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cylinder_14.geometry} material={nodes.Cylinder_14.material} position={[-0.282, 45.085, -0.011]} rotation={[Math.PI / 2, 0, 0]} scale={1.559} />
        </group>
        <group position={[-675.025, -261.882, -1335.675]}>
          <mesh geometry={nodes.Cylinder_16.geometry} material={nodes.Cylinder_16.material} position={[18.697, -45.078, 68.822]} rotation={[0, Math.PI / 2, 0]} scale={[1, 1.999, 1]} />
          <mesh geometry={nodes.Cylinder_17.geometry} material={nodes.Cylinder_17.material} position={[529.499, 0, -65.794]} rotation={[0, Math.PI / 2, 0]} scale={[1, 1.999, 1]} />
          <mesh geometry={nodes.Cylinder_15.geometry} material={nodes.Cylinder_15.material} position={[-492.628, 0, -65.794]} rotation={[0, Math.PI / 2, 0]} scale={[1, 1.999, 1]} />
          <mesh geometry={nodes.Cylinder_13.geometry} material={nodes.Cylinder_13.material} position={[-748.12, -5.593, 203.048]} rotation={[Math.PI / 2, 0, 0]} scale={1.559} />
          <mesh geometry={nodes.Cube_34.geometry} material={nodes.Cube_34.material} position={[-748.12, -56.262, 360.52]} rotation={[-Math.PI / 2, 0, 0]} scale={1.559} />
          <mesh geometry={nodes.Cube_33.geometry} material={nodes.Cube_33.material} position={[-748.12, -56.262, 45.138]} rotation={[-Math.PI / 2, 0, 0]} scale={1.559} />
          <mesh geometry={nodes.Cylinder_12.geometry} material={nodes.Cylinder_12.material} position={[18.697, -57.03, 0]} rotation={[0, -Math.PI / 2, 0]} scale={1.559} />
          <mesh geometry={nodes.Cylinder_11.geometry} material={nodes.Cylinder_11.material} position={[-492.628, -57.03, 0]} rotation={[0, Math.PI / 2, 0]} scale={1.559} />
          <mesh geometry={nodes.Cylinder_10_2.geometry} material={nodes.Cylinder_10_2.material} position={[529.499, -57.03, 0]} rotation={[0, Math.PI / 2, 0]} scale={1.559} />
        </group>
        <group position={[1476.942, -267.164, -589.022]}>
          <group position={[0, 0.771, -109.628]} rotation={[0, 0.698, 0]}>
            <mesh geometry={nodes.Rectangle_3.geometry} material={nodes.Rectangle_3.material} position={[-82.818, -26.425, 51.438]} />
            <mesh geometry={nodes.Rectangle_2.geometry} material={nodes.Rectangle_2.material} position={[-82.818, -26.425, 50.422]} />
            <mesh geometry={nodes.Cube_33_1.geometry} material={nodes.Cube_33_1.material} position={[-0.98, -29.735, -17.09]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <group position={[-14.15, 0.771, 201.569]}>
            <mesh geometry={nodes.Triangle_10.geometry} material={nodes.Triangle_10.material} position={[-81.622, -83.708, -40.94]} rotation={[-Math.PI / 2, 0, -1.339]} />
            <mesh geometry={nodes.Cylinder_30_1.geometry} material={nodes.Cylinder_30_1.material} position={[-64.147, -23.205, -51.369]} rotation={[-0.744, -0.601, -1.563]} />
            <mesh geometry={nodes.Boolean_17.geometry} material={nodes.Boolean_17.material} position={[8.915, -42.407, 7.657]} rotation={[-1.52, 0.071, 0.324]} />
            <mesh geometry={nodes.Cube_63.geometry} material={nodes.Cube_63.material} position={[49.373, -69.27, -37.25]} rotation={[0, 1.222, -Math.PI]} scale={[1.414, 1, 1.414]} />
            <mesh geometry={nodes.Rectangle_3_1.geometry} material={nodes.Rectangle_3_1.material} position={[-82.818, -26.425, 51.438]} />
            <mesh geometry={nodes.Rectangle_2_1.geometry} material={nodes.Rectangle_2_1.material} position={[-82.818, -26.425, 50.422]} />
            <mesh geometry={nodes.Cube_33_2.geometry} material={nodes.Cube_33_2.material} position={[-0.98, -29.735, -17.09]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
        </group>
        <group position={[416.655, -304.292, -1011.076]}>
          <mesh geometry={nodes.Cube_28_1.geometry} material={nodes.Cube_28_1.material} position={[-81.327, -34.576, 57.767]} rotation={[-Math.PI, 0.576, 0]} scale={0.78} />
          <mesh geometry={nodes.Cube_28_2.geometry} material={nodes.Cube_28_2.material} position={[32.642, -31.371, -38.625]} rotation={[-Math.PI, -0.31, 0]} scale={[1, 1, 0.614]} />
          <mesh geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} position={[-144.921, 5.292, 13.519]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Triangle_5.geometry} material={nodes.Triangle_5.material} position={[153.722, -45.933, -9.806]} rotation={[-Math.PI / 2, 0, -0.302]} scale={0.78} />
          <mesh geometry={nodes.Boolean_16_2.geometry} material={nodes.Boolean_16_2.material} position={[-33.781, -35.479, -47.174]} rotation={[0, 1.457, 0]} />
        </group>
        <group position={[-838.351, -304.784, 1029.625]}>
          <group position={[75.02, -44.064, 110.294]} rotation={[0, -1.227, 0]} scale={0.342}>
            <mesh geometry={nodes.Sphere_3_5.geometry} material={nodes.Sphere_3_5.material} position={[27.73, 21.116, -34.394]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Sphere_3_6.geometry} material={nodes.Sphere_3_6.material} position={[-30.187, 21.116, -34.394]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Cube_35.geometry} material={nodes.Cube_35.material} position={[0, -3.808, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <mesh geometry={nodes.Cube_51.geometry} material={nodes.Cube_51.material} position={[-22.021, -19.716, -86.767]} rotation={[-Math.PI / 2, 0, -0.01]} />
          <mesh geometry={nodes.Cube_51_1.geometry} material={nodes.Cube_51_1.material} position={[-77.119, -19.716, -112.393]} rotation={[-Math.PI / 2, 0, -0.661]} />
          <mesh geometry={nodes.Cube_51_2.geometry} material={nodes.Cube_51_2.material} position={[-12.294, 29.284, 45.475]} rotation={[-Math.PI / 2, 0, -0.539]} />
          <mesh geometry={nodes.Cube_51_3.geometry} material={nodes.Cube_51_3.material} position={[-12.294, -19.716, 45.475]} rotation={[-Math.PI / 2, 0, -0.766]} />
        </group>
        <group position={[-460.804, -329.593, -636.418]}>
          <group position={[75.887, 4.592, -105.398]} rotation={[0, -Math.PI / 4, -Math.PI / 2]} scale={0.342}>
            <mesh geometry={nodes.Sphere_7_2.geometry} material={nodes.Sphere_7_2.material} position={[-29.857, 21.116, 50.83]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Sphere_6_2.geometry} material={nodes.Sphere_6_2.material} position={[-29.857, 21.116, -55.442]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Cube_7_3.geometry} material={nodes.Cube_7_3.material} position={[7.983, -3.808, 10.947]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <group position={[-116.114, -18.782, 169.687]} scale={0.342}>
            <mesh geometry={nodes.Sphere_6_3.geometry} material={nodes.Sphere_6_3.material} position={[-38.097, 19.761, -34.394]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Sphere_5_1.geometry} material={nodes.Sphere_5_1.material} position={[12.159, 19.761, -34.394]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Cube_14_3.geometry} material={nodes.Cube_14_3.material} position={[0, -5.163, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <group position={[116.828, -18.91, -174.313]} scale={0.342}>
            <mesh geometry={nodes.Sphere_12_1.geometry} material={nodes.Sphere_12_1.material} position={[22.591, 21.116, -31.618]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Cube_21_1.geometry} material={nodes.Cube_21_1.material} position={[12.635, -3.808, -27.135]} rotation={[-Math.PI / 2, 0, 0]} />
            <mesh geometry={nodes.Sphere_13_5.geometry} material={nodes.Sphere_13_5.material} position={[-23.205, 21.116, -31.618]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
          </group>
        </group>
        <group position={[-572.283, -290.783, 732.452]} scale={[1, 1, 0.996]}>
          <group position={[77.924, -19.165, -63.525]}>
            <mesh geometry={nodes.Sphere_18.geometry} material={nodes.Sphere_18.material} position={[0, 25.364, 0]} rotation={[-Math.PI / 2, 0, 0]} />
            <mesh geometry={nodes.Cube_3_8.geometry} material={nodes.Cube_3_8.material} position={[0, -25.364, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <group position={[137.85, 8.969, -12.767]} scale={0.703}>
            <mesh geometry={nodes.Cone_3_4.geometry} material={nodes.Cone_3_4.material} position={[0, 54.674, 0]} />
            <mesh geometry={nodes.Cone_2_4.geometry} material={nodes.Cone_2_4.material} position={[0, 24.584, 0]} />
            <mesh geometry={nodes.Cone_14.geometry} material={nodes.Cone_14.material} position={[0, -6.58, 0]} />
            <mesh geometry={nodes.Cylinder_3_3.geometry} material={nodes.Cylinder_3_3.material} position={[0.624, -72.792, -0.984]} />
          </group>
          <group position={[-204.032, -58.132, 239.365]} scale={0.342}>
            <mesh geometry={nodes.Sphere_10_2.geometry} material={nodes.Sphere_10_2.material} position={[3.159, 21.339, -56.041]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Cube_26_1.geometry} material={nodes.Cube_26_1.material} position={[52.793, -3.585, -26.115]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <group position={[162.25, -57.593, 84.87]} scale={0.342}>
            <mesh geometry={nodes.Sphere_14_3.geometry} material={nodes.Sphere_14_3.material} position={[-24.675, 19.761, -34.96]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Sphere_13_6.geometry} material={nodes.Sphere_13_6.material} position={[21.124, 19.761, -34.96]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Cube_23_1.geometry} material={nodes.Cube_23_1.material} position={[0, -5.163, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <group position={[-34.062, -29.524, 134.214]} rotation={[Math.PI / 2, 0, 0]} scale={0.342}>
            <mesh geometry={nodes.Cube_15_2.geometry} material={nodes.Cube_15_2.material} position={[13.234, -3.808, 0]} rotation={[-Math.PI / 2, 0, 0]} />
            <mesh geometry={nodes.Sphere_5_2.geometry} material={nodes.Sphere_5_2.material} position={[-30.285, 21.116, -34.394]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
          </group>
          <group position={[-39.872, -29.524, 105.681]} rotation={[1.92, 0, -Math.PI / 2]} scale={0.342}>
            <mesh geometry={nodes.Sphere_4_4.geometry} material={nodes.Sphere_4_4.material} position={[6.205, 21.116, -34.394]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
            <mesh geometry={nodes.Cube_6_2.geometry} material={nodes.Cube_6_2.material} position={[0, -3.808, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <mesh geometry={nodes['3'].geometry} material={nodes['3'].material} position={[-107.353, -53.632, 161.385]} rotation={[-Math.PI / 2, 0, 1.322]} scale={2.64} />
          <mesh geometry={nodes.Boolean_16_3.geometry} material={nodes.Boolean_16_3.material} position={[175.526, -48.989, -228.394]} rotation={[0, 0.461, 0]} />
          <mesh geometry={nodes.Cone.geometry} material={nodes.Cone.material} position={[205.194, -33.717, -101.583]} />
          <mesh geometry={nodes.Pyramid.geometry} material={nodes.Pyramid.material} position={[71.884, -33.717, -9.189]} />
        </group>
        <group position={[277.385, -320.831, -191.629]} rotation={[Math.PI / 2, 0, 0]} scale={0.342}>
          <mesh geometry={nodes.Sphere_2.geometry} material={nodes.Sphere_2.material} position={[40.527, 21.116, -26.826]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
          <mesh geometry={nodes.Sphere_1.geometry} material={nodes.Sphere_1.material} position={[-17.391, 21.116, -26.826]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 0.405]} />
          <mesh geometry={nodes.Cube_2_1.geometry} material={nodes.Cube_2_1.material} position={[0, -3.808, 7.567]} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <directionalLight intensity={1} decay={2} rotation={[-0.836, -0.187, -1.405]} />
        <directionalLight intensity={1} decay={2} rotation={[-0.698, -0.662, -0.938]} />
        <PerspectiveCamera makeDefault={false} far={100000} near={70} fov={45} position={[611.931, 934.767, 1241.475]} rotation={[-0.645, 0.375, 0.269]} />
        <directionalLight intensity={0.7} decay={2} rotation={[-0.697, 0.591, 0.983]} />
        <PerspectiveCamera makeDefault={false} far={100000} near={5} fov={45} position={[-669.566, 611.875, 1862.462]} rotation={[-0.307, -0.138, -0.044]} />
        <PerspectiveCamera makeDefault={false} far={100000} near={5} fov={45} position={[-137.62, 661.632, 2543.408]} rotation={[-0.243, 0.11, 0.027]} />
        <mesh geometry={nodes.Text_2.geometry} material={nodes.Text_2.material} position={[118.748, -258.617, 0]} />
        <mesh geometry={nodes.Text_2_1.geometry} material={nodes.Text_2_1.material} position={[-32.049, -280.223, 0]} />
        <mesh geometry={nodes.Text_2_2.geometry} material={nodes.Text_2_2.material} position={[34.345, -280.223, 0]} />
        <mesh geometry={nodes.Text_2_3.geometry} material={nodes.Text_2_3.material} position={[273.15, -280.223, 0]} />
        <mesh geometry={nodes.Text_2_4.geometry} material={nodes.Text_2_4.material} position={[203.775, -280.223, 0]} />
        <mesh geometry={nodes.Text_2_5.geometry} material={nodes.Text_2_5.material} position={[-97.207, -280.223, 0]} />
        <mesh geometry={nodes.Text_2_6.geometry} material={nodes.Text_2_6.material} position={[-167.671, -280.223, 0]} />
        <mesh geometry={nodes.Text_2_7.geometry} material={nodes.Text_2_7.material} position={[-242.666, -281.771, 0]} />
        <mesh geometry={nodes.Text_2_8.geometry} material={nodes.Text_2_8.material} position={[-337.453, -291.53, 0]} />
        <mesh geometry={nodes.Text_2_9.geometry} material={nodes.Text_2_9.material} position={[-455.345, -291.53, 0]} />
        <mesh geometry={nodes.Text_2_10.geometry} material={nodes.Text_2_10.material} position={[-531.159, -291.53, 0]} />
        <mesh geometry={nodes.Text_2_11.geometry} material={nodes.Text_2_11.material} position={[-608.525, -291.53, 0]} />
        <mesh geometry={nodes.Text_2_12.geometry} material={nodes.Text_2_12.material} position={[-679.831, -291.53, 0]} />
        <mesh geometry={nodes.Text_2_13.geometry} material={nodes.Text_2_13.material} position={[-759.812, -284.268, 0]} />
        <mesh geometry={nodes.Text_2_14.geometry} material={nodes.Text_2_14.material} position={[-879.963, -291.53, 0]} />
        <mesh geometry={nodes.Text_2_15.geometry} material={nodes.Text_2_15.material} position={[-951.226, -291.53, 0]} />
        <mesh geometry={nodes.Text_2_16.geometry} material={nodes.Text_2_16.material} position={[-1018.902, -291.53, 0]} />
        <mesh geometry={nodes.Text_2_17.geometry} material={nodes.Text_2_17.material} position={[-1122.544, -291.53, 0]} />
        <mesh geometry={nodes.Text.geometry} material={nodes.Text.material} position={[45.966, -300.727, -200]} />
        <mesh geometry={nodes.Text_1.geometry} material={nodes.Text_1.material} position={[-97.319, -300.727, -200]} />
        <mesh geometry={nodes.Text_3.geometry} material={nodes.Text_3.material} position={[-240.428, -300.727, -200]} />
        <mesh geometry={nodes.Text_4.geometry} material={nodes.Text_4.material} position={[-379.158, -300.727, -200]} />
        <mesh geometry={nodes.Text_5.geometry} material={nodes.Text_5.material} position={[-520.517, -300.727, -200]} />
        <mesh geometry={nodes.Text_6.geometry} material={nodes.Text_6.material} position={[-625.159, -300.727, -200]} />
        <mesh geometry={nodes.Text_7.geometry} material={nodes.Text_7.material} position={[-720.187, -300.727, -200]} />
        <mesh geometry={nodes.Text_8.geometry} material={nodes.Text_8.material} position={[-815.053, -300.727, -200]} />
        <mesh geometry={nodes.Text_9.geometry} material={nodes.Text_9.material} position={[-956.441, -300.727, -200]} />
        <mesh geometry={nodes.Text_10.geometry} material={nodes.Text_10.material} position={[-1113.109, -300.727, -200]} />
        <mesh geometry={nodes.Rectangle.geometry} material={nodes.Rectangle.material} position={[710.969, -348.12, 23.845]} rotation={[-Math.PI / 2, 0, 0.629]} />
        <mesh geometry={nodes.Ball.geometry} material={nodes.Ball.material} position={[-415, 58.345, 508.926]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.ground.geometry} material={nodes.ground.material} position={[67.84, -349.49, -81.5]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Cylinder_23.geometry} material={nodes.Cylinder_23.material} position={[247.085, -237.63, 1424.139]} scale={[1, 0.5, 1]} />
        <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[614.437, -318.144, -93.001]} rotation={[-Math.PI / 2, 0, 0]} scale={1.559} />
      </group>
    </group>
  )
}

useGLTF.preload('/port.gltf')
